name: hrms_mobile_app
description: A Hotel and Restaurant Management System mobile application.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # State Management
  provider: ^6.1.2

  # Local Storage
  shared_preferences: ^2.3.3

  # HTTP Client
  dio: ^5.4.3+1
  http: ^1.2.1

  # UI & Fonts
  google_fonts: ^6.2.1

  # Authentication
  google_sign_in: ^6.2.1

  # Payment Processing
  flutter_stripe: ^10.1.1

  # Date & Time Formatting
  intl: ^0.19.0

  # UUID Generation
  uuid: ^4.4.0

  # Charts
  fl_chart: ^0.68.0

  # Location Services
  geolocator: ^12.0.0
  geocoding: ^3.0.0

  # Socket.IO Client
  socket_io_client: ^2.0.3+1

  # Calendar
  table_calendar: ^3.1.2

  # QR Code
  qr_flutter: ^4.1.0

  # Material Design Icons (Recommended with Material 3)
  material_design_icons_flutter: ^7.0.7296

  # Utilities
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
        - asset: fonts/Poppins-Bold.ttf
          weight: 700
